# Test Makefile for kernel source demo
obj-$(CONFIG_USB) += usb-core.o
obj-$(CONFIG_NET) += network.o
obj-$(CONFIG_SCSI) += scsi-subsystem.o

# Subdirectories
obj-$(CONFIG_USB) += drivers/
obj-$(CONFIG_NET) += net/
