# GitHub Actions workflow for VEX Kernel Checker
name: VEX Kernel Checker CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['v3.7', 'v3.8', 'v3.9', 'v3.10', 'v3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        make install-dev
    
    - name: Run quick smoke tests
      run: |
        make test-quick
    
    - name: Run unit tests with coverage
      run: |
        make test-coverage
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.9'  # Only upload once
      with:
        file: htmlcov/coverage.xml
        flags: unittests

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install linting tools
      run: |
        make install-dev
    
    - name: Lint with flake8
      run: |
        make lint
    
    - name: Check formatting with black
      run: |
        make format-check

  performance:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        make install-dev
    
    - name: Run performance benchmarks
      run: |
        make ci-benchmark
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmark_results.json

  integration:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        make install
    
    - name: Create test kernel structure
      run: |
        make setup-test-data
        echo '{"vulnerabilities":[{"id":"CVE-2023-1234","severity":"HIGH"}]}' > test.vex
    
    - name: Test tool functionality (config-only mode)
      run: |
        make run-example
